name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/common.yml
    with:
      do_deploy: true
